# src/Blogger/BlogBundle/Resources/config/config.yml
parameters:
    # Blogger contact email address
    blogger_blog.emails.contact_email: patrickvanefferen@gmail.com

    # Blogger max Latest comments
    blogger_blog.comments.latest_comment_limit: 10